package com.contactapp.controller;

import com.contactapp.model.Person;
import com.contactapp.db.PersonDAO;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert;

/**
 * Controller for adding new persons.
 */
public class AddPersonController {
    
    @FXML
    private TextField firstNameField;
    
    @FXML
    private TextField lastNameField;
    
    @FXML
    private TextField nicknameField;
    
    @FXML
    private TextField phoneField;
    
    @FXML
    private TextField addressField;
    
    @FXML
    private TextField emailField;
    
    @FXML
    private TextField birthDateField;
    
    private PersonDAO dao = new PersonDAO();
    
    /**
     * Handle save button click - saves the new contact to database
     */
    @FXML
    private void handleSave() {
        // Validate inputs
        if (firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty()) {
            showAlert("Validation Error", "First name and last name are required!");
            return;
        }
        
        // Create new Person object
        Person person = new Person(
                0,  // ID will be auto-generated by database
                lastNameField.getText(),
                firstNameField.getText(),
                nicknameField.getText(),
                phoneField.getText(),
                addressField.getText(),
                emailField.getText(),
                birthDateField.getText()
        );
        
        // Insert into database
        dao.insertPerson(person);
        
        // Show success message
        showAlert("Success", "Contact added successfully!");
        
        // Clear fields
        clearFields();
        
        // Go back to main view
        goBackToMainView();
    }
    
    /**
     * Handle cancel button click - goes back to main view without saving
     */
    @FXML
    private void handleCancel() {
        goBackToMainView();
    }
    
    /**
     * Clear all text fields
     */
    private void clearFields() {
        firstNameField.clear();
        lastNameField.clear();
        nicknameField.clear();
        phoneField.clear();
        addressField.clear();
        emailField.clear();
        birthDateField.clear();
    }
    
    /**
     * Navigate back to main view
     */
    private void goBackToMainView() {
        try {
            com.contactapp.Main.showView("MainWindow");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * Show alert dialog
     */
    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}