package com.contactapp.controller;

import com.contactapp.model.Person;
import com.contactapp.db.PersonDAO;
import com.contactapp.util.DateUtil;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert;
import javafx.scene.control.DatePicker;

/**
 * Controller for the Add Contact form.
 * Handles creating new contacts and saving them to the database.
 */
public class AddPersonController {
    
    // Form input fields
    @FXML
    private TextField firstNameField;
    
    @FXML
    private TextField lastNameField;
    
    @FXML
    private TextField nicknameField;
    
    @FXML
    private TextField phoneField;
    
    @FXML
    private TextField addressField;
    
    @FXML
    private TextField emailField;
    
    @FXML
    private DatePicker birthDatePicker;
    
    private PersonDAO dao = new PersonDAO();
    
    /**
     * Save the new contact to the database.
     * Validates required fields, creates a Person object, and stores it.
     */
    @FXML
    private void handleSave() {
        // Check that first and last name are filled in
        if (firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty()) {
            showAlert("Validation Error", "First name and last name are required!");
            return;
        }
        
        // Create a new contact with form data
        Person person = new Person(
                0,  // ID is auto-generated by database
                lastNameField.getText(),
                firstNameField.getText(),
                nicknameField.getText(),
                phoneField.getText(),
                addressField.getText(),
                emailField.getText(),
                DateUtil.toDbString(birthDatePicker.getValue())
        );
        
        // Save the contact to database
        dao.insertPerson(person);
        
        // Confirm success to user
        showAlert("Success", "Contact added successfully!");
        
        // Reset form fields
        clearFields();
        
        // Return to main contact list
        goBackToMainView();
    }
    
    /**
     * Cancel adding a new contact and return to main view.
     */
    @FXML
    private void handleCancel() {
        goBackToMainView();
    }
    
    /**
     * Clear all form fields to prepare for new entry.
     */
    private void clearFields() {
        firstNameField.clear();
        lastNameField.clear();
        nicknameField.clear();
        phoneField.clear();
        addressField.clear();
        emailField.clear();
        birthDatePicker.setValue(null);
    }
    
    /**
     * Navigate back to the main contact list view.
     */
    private void goBackToMainView() {
        try {
            com.contactapp.Main.showView("MainWindow");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * Display a popup message to the user.
     * 
     * @param title The title of the alert window
     * @param message The message to display
     */
    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}